name: PROD IaC deployment

on:
  push:
    branches:
      - main
    paths:
      - aws/terraform/environments/prod/**
  pull_request:
    branches:
      - main
    paths:
      - aws/terraform/environments/prod/**

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: prod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
